name: Build


on:
    workflow_dispatch:
    push: 


jobs:
    build:
        name: ${{ matrix.arch }} build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch:
                - x86_64
                - aarch64_cortex-a53
    
        steps:
        - name: Building packages
          uses: actions/checkout@main


        - name: Build
          uses: openwrt/gh-action-sdk@main
          env:
              ARCH: ${{ matrix.arch }}-openwrt-22.03
              FEEDNAME: packages_ci
              PACKAGES: luci-app-vlmcsd
              NO_REFRESH_CHECK: true

        - name: Store packages
          uses: actions/upload-artifact@main
          with:
           name: luci-app-vlmcsd-${{ matrix.arch}}
           path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

        - name: Delete workflow runs
          uses: AoThen/delete-workflow-runs@main
          with:
                retain_days: 1
                keep_minimum_runs: 5


# name: "Build"

# on:
#   push:


# permissions:
#   contents: write # for Git to git push

# jobs:
#   job_build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Building packages
#         uses: actions/checkout@main

#       - name: Install packages
#         run: |
#           git config --global user.email ${{ secrets.EMAIL }}
#           git config --global user.name ${{ secrets.NAME }}
#           git clone --depth 1 https://github.com/siwind/luci-app-vlmcsd.git
#           rm -rf luci-app-vlmcsd/.git
#           git add .
#           git commit -m "update luci-app-vlmcsd"
#           git push "https://${{ secrets.NAME }}:${{ github.token }}@github.com/${{ github.repository }}.git" master
