name: "Build"

on:
  push:


permissions:
  contents: write # for Git to git push

jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Building packages
        uses: actions/checkout@main

      - name: Install packages
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git clone --depth 1 https://github.com/siwind/luci-app-vlmcsd.git
          rm -rf luci-app-vlmcsd/.git
          git add .
          git commit -m "update luci-app-vlmcsd"
          git push "https://${{ secrets.NAME }}:${{ github.token }}@github.com/${{ github.repository }}.git" master
